name: docker-build

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Clone and checkout branch
              uses: actions/checkout@v2

            - name: Set up Python version
              uses: actions/setup-python@v2
              with:
                python-version: '3.11'

            - name: Set environment variables
              run: |
                echo "BACKOFFICE_BACKEND_APP=${{ secrets.BACKOFFICE_BACKEND_APP }}" >> $GITHUB_ENV
                echo "BACKOFFICE_BACKEND_APP_HOST=${{ secrets.BACKOFFICE_BACKEND_APP_HOST }}" >> $GITHUB_ENV
                echo "BACKOFFICE_BACKEND_APP_PORT=${{ secrets.BACKOFFICE_BACKEND_APP_PORT }}" >> $GITHUB_ENV
                echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
                echo "QUICKSTORE_BACKEND_APP=${{ secrets.QUICKSTORE_BACKEND_APP }}" >> $GITHUB_ENV
                echo "QUICKSTORE_BACKEND_APP_HOST=${{ secrets.QUICKSTORE_BACKEND_APP_HOST }}" >> $GITHUB_ENV
                echo "QUICKSTORE_BACKEND_APP_PORT=${{ secrets.QUICKSTORE_BACKEND_APP_PORT }}" >> $GITHUB_ENV

            - name: Build project
              run: make build

            - name: Run tests
              run: make test

    build:
        needs: tests

        runs-on: ubuntu-latest

        steps:
            - name: Clone and checkout branch
              uses: actions/checkout@v2

            - name: Build docker image
              run: docker build -t test-tag .