name: docker-build

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Clone and checkout branch
              uses: actions/checkout@v2

            - name: Set up Python version
              uses: actions/setup-python@v2
              with:
                python-version: '3.11'

            - name: Build project
              env:
                BACKOFFICE_MONGODB_URI: ${{ secrets.BACKOFFICE_MONGODB_URI }}
                BACKOFFICE_BACKEND_APP: ${{ secrets.BACKOFFICE_BACKEND_APP }}
                BACKOFFICE_BACKEND_APP_HOST: ${{ secrets.BACKOFFICE_BACKEND_APP_HOST }}
                BACKOFFICE_BACKEND_APP_PORT: ${{ secrets.BACKOFFICE_BACKEND_APP_PORT }}
              run: make build

            - name: Run tests
              env:
                BACKOFFICE_MONGODB_URI: ${{ secrets.BACKOFFICE_MONGODB_URI }}
                BACKOFFICE_BACKEND_APP: ${{ secrets.BACKOFFICE_BACKEND_APP }}
                BACKOFFICE_BACKEND_APP_HOST: ${{ secrets.BACKOFFICE_BACKEND_APP_HOST }}
                BACKOFFICE_BACKEND_APP_PORT: ${{ secrets.BACKOFFICE_BACKEND_APP_PORT }}
              run: make test

    build:
        needs: tests

        runs-on: ubuntu-latest

        steps:
            - name: Clone and checkout branch
              uses: actions/checkout@v2

            - name: Build docker image
              run: docker build -t test-tag .