name: tests

on:
    push:
    pull_request:
    schedule:
        - cron: '15 10 * * 6'

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: [ '3.10', '3.11' ]
        steps:
            - name: Clone and checkout branch
              uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}

            - name: Set environment variables
              run: |
                echo "BACKOFFICE_BACKEND_APP=${{ secrets.BACKOFFICE_BACKEND_APP }}" >> $GITHUB_ENV
                echo "BACKOFFICE_BACKEND_APP_HOST=${{ secrets.BACKOFFICE_BACKEND_APP_HOST }}" >> $GITHUB_ENV
                echo "BACKOFFICE_BACKEND_APP_PORT=${{ secrets.BACKOFFICE_BACKEND_APP_PORT }}" >> $GITHUB_ENV
                echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
                echo "QUICKSTORE_BACKEND_APP=${{ secrets.QUICKSTORE_BACKEND_APP }}" >> $GITHUB_ENV
                echo "QUICKSTORE_BACKEND_APP_HOST=${{ secrets.QUICKSTORE_BACKEND_APP_HOST }}" >> $GITHUB_ENV
                echo "QUICKSTORE_BACKEND_APP_PORT=${{ secrets.QUICKSTORE_BACKEND_APP_PORT }}" >> $GITHUB_ENV

            - name: Build project
              run: make build

            - name: Run tests
              run: make test