name: tests

on:
    push:
    pull_request:
    schedule:
        - cron: '15 10 * * 6'

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: [ '3.10', '3.11' ]
        steps:
            - name: Clone and checkout branch
              uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}

            - name: Build project
              env:
                BACKOFFICE_MONGODB_URI: ${{ secrets.BACKOFFICE_MONGODB_URI }}
                BACKOFFICE_BACKEND_APP: ${{ secrets.BACKOFFICE_BACKEND_APP }}
                BACKOFFICE_BACKEND_APP_HOST: ${{ secrets.BACKOFFICE_BACKEND_APP_HOST }}
                BACKOFFICE_BACKEND_APP_PORT: ${{ secrets.BACKOFFICE_BACKEND_APP_PORT }}
              run: make build

            - name: Run tests
              env:
                BACKOFFICE_MONGODB_URI: ${{ secrets.BACKOFFICE_MONGODB_URI }}
                BACKOFFICE_BACKEND_APP: ${{ secrets.BACKOFFICE_BACKEND_APP }}
                BACKOFFICE_BACKEND_APP_HOST: ${{ secrets.BACKOFFICE_BACKEND_APP_HOST }}
                BACKOFFICE_BACKEND_APP_PORT: ${{ secrets.BACKOFFICE_BACKEND_APP_PORT }}
              run: make test